### ISSUE TITLE
Update KaTeX version to 0.15.0 and later

### ISSUE THREAD

**Issue by ipratt-code** [kwshi/rehype-katex-svelte#2]
Currently, this library supports KaTeX of the version of 0.12.0. However, the latest version of KaTeX is 0.15.2. Is there any specific reason why this library is still using version 0.12.0? Or can it be updated?

**Comment by kwshi** [comment]
(I ask because in the process of updating dependencies a handful of other libraries also became esmodule-only, so I had to make this library esm-only also, but that may break some existing usages, which I haven't had the chance to test out yet.

**Comment by ipratt-code** [comment]
Sorry for the delay! I was doing some personal things and events with family, school, etc. However, I tried it and I do have an error that occurs for only the 1.1.0 version:
```
> my-website@0.0.1 dev
> svelte-kit dev

(node:7114) UnhandledPromiseRejectionWarning: file:///home/ianp/Git/my-website/node_modules/rehype-katex-svelte/dist/index.js:13
import hastToString from "hast-util-to-string";
       ^^^^^^^^^^^^
SyntaxError: The requested module 'hast-util-to-string' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async load_config (file:///home/ianp/Git/my-website/node_modules/@sveltejs/kit/dist/cli.js:911:17)
    at async file:///home/ianp/Git/my-website/node_modules/@sveltejs/kit/dist/cli.js:1013:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
my package.json looks like this:
```json
{
  "name": "my-website",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/adapter-static": "^1.0.0-next.26",
    "@sveltejs/kit": "next",
    "mdsvex": "^0.10.5",
    "rehype-katex-svelte": "^1.1.0",
    "remark-math": "^3.0.0",
    "svelte": "^3.44.0",
    "sveltejs-adapter-ipfs": "^0.2.1"
  },
  "type": "module"
}
```
my svelte.config.js file looks like this:
```js
import { mdsvex } from "mdsvex";
import mdsvexConfig from "./mdsvex.config.js";
import adapter from "sveltejs-adapter-ipfs"; //"@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  extensions: [".svelte", ...mdsvexConfig.extensions],
  extensions: [".svelte", ".md"],

  kit: {
    // Default SvelteKit options
    // target: "#svelte",
    adapter: adapter(),
  },

  preprocess: [mdsvex(mdsvexConfig)],
};

export default config;
```
my mdsvex.config.js file looks like this:
```js
import { defineMDSveXConfig as defineConfig } from "mdsvex";
import rehypeKatexSvelte from "rehype-katex-svelte";
import remarkMath from "remark-math";

const config = defineConfig({
  extensions: [".md"],

  smartypants: {
    quotes: false,
    ellipses: false,
    dashes: "oldschool",
  },

  layout: {
    posts: "./src/routes/posts/layout.svelte",
    //projects: "./src/routes/projects/layout.svelte"
  },

  remarkPlugins: [remarkMath],

  rehypePlugins: [rehypeKatexSvelte],
});

export default config;
```
Do you have any idea what is going on?
Thanks in advance!

**Comment by ipratt-code** [comment]
Hey, what do you know, it worked! To make sure i was using the latest version, i inserted into my testing page `$\kern2\relax em$`, which produced an error. This is the [intended behavior for 0.15.0 and up](https://github.com/KaTeX/KaTeX/releases/tag/v0.15.0), so I know that it works! Thanks for all the help!
